version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: efile941_app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://2.29.8.150:10691/efile941_db
      - DB_USER=postgres
      - DB_PASS=root
      - IRS_MEF_EFIN=10-1234
      - IRS_MEF_ETIN=12345
      - AUTHORIZENET_ENVIRONMENT=SANDBOX

  db:
    image: postgres:17-alpine
    container_name: efile941_db
    environment:
      POSTGRES_DB: efile941_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "10691:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d efile941_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
